version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: maven_app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/crud_db
      DB_USER: appuser
      DB_PASSWORD: apppass
    working_dir: /usr/src/app
    command: >
      mvn clean package liquibase:update